# This file is for project maintainer only.
# See https://sparanoid.com/lab/amsf/getting-started.html#method-run-in-docker to learn how to
# create your own `docker-compose.yml`
version: '3'

x-defaults: &defaults
  build:
    context: .
    dockerfile: Dockerfile
  image: sparanoid/amsf:latest
  restart: always
  volumes:
    - ./:/opt/amsf/
  ports:
    - "4321:4321"

services:
  amsf:
    <<: *defaults
    command: serve
